title: "Radios"
author: "Gean Ramos"
email: "radios@geanramos.com.br"
description: "descricao em breve"
permalink: ':title.html'
image: "https://picsum.photos/600/363" #https://picsum.photos/600/363
logo: "https://avatars.githubusercontent.com/u/6352393?v=4"
baseurl: "/radio"
url: "https://dev.gean.me"
theme: minima
markdown: kramdown
paginate: 10


